name: Build, Test and Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: '5.x'
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - name: List directory contents
        run: ls -la
        working-directory: Server/CarCare-Companion
      - name: Install dependencies
        run: dotnet restore
        working-directory: Server/CarCare-Companion
      - name: Build
        run: dotnet build
        working-directory: Server/CarCare-Companion
      - name: Run Unit Tests
        run: dotnet test --filter Category=Unit --no-restore --verbosity normal
        working-directory: Server/CarCare-Companion
      - name: Copy Unit Test Results
        run: mkdir TestResults; cp Server/CarCare-Companion/CarCare-Companion.Tests/TestResults/CarCare-Companion.Tests.trx TestResults/
        shell: bash
      - name: Build container
        run: docker build -t pisarev/carcarecompanionapi .
        working-directory: Server/CarCare-Companion
      - name: Wait for docker container to build
        run: sleep 30s
      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build
        env:
          VERSION: ${{ steps.gitversion.outputs.nuGetVersion }}
      - name: Wait for docker containers to setup
        run: sleep 30s
        shell: bash
      - name: Run Integration Tests
        run: dotnet test --filter Category=Integration --no-restore --verbosity normal
        env:
          BASE_URL: http://localhost:5200
      - name: Copy Integration Test Results
        run: mkdir TestResults; cp Server/CarCare-Companion/CarCare-Companion.Tests/TestResults/CarCare-Companion.Tests.trx TestResults/
        shell: bash
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test Results
          path: Server/CarCare-Companion/CarCare-Companion.Tests/TestResults/*.trx
          reporter: dotnet-trx
